"""Adapter for AdifExporter — formats QSOs as ADIF text. Pure string transform, no I/O."""

from __future__ import annotations

from collections.abc import Sequence

from radio_pota_logging.domain.logging_session.value_objects import Qso

_ADIF_VERSION = "3.1.4"
_HEADER = (
    f"Generated by radio_pota_logging\n<ADIF_VER:{len(_ADIF_VERSION)}>{_ADIF_VERSION}\n<EOH>\n"
)

# requirements.md Story 4: exactly these 14 fields, in this order.
_FIELD_ORDER = (
    "OPERATOR",
    "CALL",
    "QSO_DATE",
    "TIME_ON",
    "TIME_OFF",
    "BAND",
    "MODE",
    "MY_SIG",
    "MY_SIG_INFO",
    "RST_SENT",
    "RST_RCVD",
    "FREQ",
    "MY_RIG",
    "TX_PWR",
)


class AdifFileExporter:
    """Implements AdifExporter against the ADIF 3.x text format."""

    def export(self, qsos: Sequence[Qso]) -> str:
        records = "\n".join(_format_record(qso) for qso in qsos)
        return _HEADER + records + ("\n" if records else "")


def _field(name: str, value: str) -> str:
    return f"<{name}:{len(value)}>{value}"


def _format_record(qso: Qso) -> str:
    values = {
        "OPERATOR": qso.operator,
        "CALL": qso.call,
        "QSO_DATE": qso.timestamp.qso_date.strftime("%Y%m%d"),
        "TIME_ON": qso.timestamp.time_on.strftime("%H%M%S"),
        "TIME_OFF": qso.time_off.strftime("%H%M%S"),
        "BAND": qso.band.value,
        "MODE": qso.mode,
        "MY_SIG": qso.my_sig,
        "MY_SIG_INFO": qso.my_sig_info,
        "RST_SENT": qso.rst_sent,
        "RST_RCVD": qso.rst_rcvd,
        "FREQ": str(qso.freq.megahertz),
        "MY_RIG": qso.my_rig,
        "TX_PWR": qso.tx_pwr,
    }
    fields = " ".join(_field(name, values[name]) for name in _FIELD_ORDER)
    return f"{fields} <EOR>"
